apiVersion: v1
kind: ServiceAccount
metadata:
  name: trae-agent-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trae-agent-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trae-agent-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: trae-agent-sa
  namespace: default
roleRef:
  kind: Role
  name: trae-agent-role
  apiGroup: rbac.authorization.k8s.io
